from pgym.pf_cases.case3 import case as org_case3
from pgym.pf_cases.case5m import case as org_case5m
from pgym.pf_cases.case5bw import case as org_case5bw
from pgym.pf_cases.case30 import case as org_case30
from pgym.pf_cases.case33bw import case as org_case33bw
from pgym.pf_cases.case18 import case as org_case18
from pgym.pf_cases.case22 import case as org_case22
from pgym.pf_cases.case69 import case as org_case69
from pgym.pf_cases.case85 import case as org_case85
from pgym.pf_cases.case141 import case as org_case141

from pgym.pf_cases.case3 import pf_case as case3
from pgym.pf_cases.case5m import pf_case as case5m
from pgym.pf_cases.case5bw import pf_case as case5bw
from pgym.pf_cases.case30 import pf_case as case30
from pgym.pf_cases.case33bw import pf_case as case33bw
from pgym.pf_cases.case18 import pf_case as case18
from pgym.pf_cases.case22 import pf_case as case22
from pgym.pf_cases.case69 import pf_case as case69
from pgym.pf_cases.case85 import pf_case as case85
from pgym.pf_cases.case141 import pf_case as case141
